### ISSUE TITLE
The `_asset` folder and image paths

### ISSUE THREAD

**Issue by marianzburlea** [varvarasd/website-1#3]
The name of the `_asset` folder present in the `src` starts with and underscore "_" so the *gulp pug* task knows to ignore it and its content. Once it gets copied it loses the "_" so the image path should be like `/asset/image/my-image-name.png`. See the image below:
      ![image](https://cloud.githubusercontent.com/assets/1318985/23684964/a0d7f958-0399-11e7-9ccc-f35c75b7464c.png)
      Example:
      ![image](https://cloud.githubusercontent.com/assets/1318985/23685007/cc4c4454-0399-11e7-855e-0e8ea9b8d970.png)

**Comment by varvarasd** [comment]
hey thanks for that I was wondering what the hell is wrong, however this was my safest bet. something wrong with the damn _ 💃
